[package]
name = "man_prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capstone = "0.11.0"
goblin = "0.8.0"
thiserror = "1.0.50"
cpp_demangle = "0.4.3"
serde_json = "1.0"
object = "0.32.2"
gimli = "0.28.1"
memmap2 = "0.9.4"
