name: heavy-tests

on:
  schedule:
    - cron: '0 21 * * 2' # Every Tuesday at 21:00 UTC

jobs:
  ffmpeg-heavy-test:
    name: Heavy Test for ffmpeg
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview
    
    - name: Set working directory and reconstruct heavy file
      working-directory: ${{ github.workspace }}/crates/backend/tests
      run: |
        cat binaries/ffmpeg_g.* > binaries/ffmpeg
        cat snapshots/heavy_test_c/functions_list.snap.part_a* > snapshots/heavy_test_c/functions_list.snap

    - name: Run Backend Integration Test
      working-directory: ${{ github.workspace }}/crates/backend/tests
      run: cargo test --test heavy_tests -- --nocapture 

    - name: Remove heavy file
      working-directory: ${{ github.workspace }}/crates/backend/tests
      run: |
        rm binaries/ffmpeg
        rm snapshots/heavy_test_c/functions_list.snap