name: heavy-tests

on:
  schedule:
    - cron: '0 21 * * 2' # Every Tuesday at 21:00 UTC

jobs:
  ffmpeg-heavy-test:
    name: Heavy Test for ffmpeg
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview

    - name: Reconstruct heavy file from parts
      run: |
        cat ../../crates/backend/tests/binaries/ffmpeg_g.* > ../../crates/backend/tests/binaries/ffmpeg
        cat ../../crates/backend/tests/snapshots/heavy_test_c/functions_list.snap.part_a* > ../../crates/backend/tests/snapshots/heavy_test_c/functions_list.snap

    - name: Run Backend Integration Test
      run: cargo test --test heavy_tests -- --nocapture 

    - name: Remove heavy file
      run: |
        rm ../../crates/backend/tests/binaries/ffmpeg
        rm ../../crates/backend/tests/snapshots/heavy_test_c/functions_list.snap